app:
  applicationId: ${YOUR_APP_ID}
  env: Development # or arbitrary string
  host: http://localhost:8000
  openApiConf:
    path: "/openapi.json"
    #filePath: "openapi.json"
  authentication:
    loggedInIndicator: "HTTP/\d+\.\d+\s+(2[0-9][0-9]|3[0-9][0-9])"
    loggedOutIndicator: "HTTP/\d+\.\d+\s+(4[0-9][0-9])"
    # authn
    script:
      name: oauth-client-credentials.js
      parameters:
        issuer: https://${YOUR_DOMAIN}/${YOUR_AUTH_API}
        grant_type: client_credentials
      credentials:
        client_id: ${YOUR_CLIENT_ID}
        client_secret: ${YOUR_CLIENT_SECRET}
    # authz
    tokenAuthorization:
      type: HEADER
      value: Authorization
    tokenExtraction:
      type: TOKEN_PATH
      value: "access_token"
      tokenType: Bearer
    testPath:
      path: /private
      success: '.*200.*'
hawkAddOn:
  scripts:
    - name: oauth-client-credentials.js
      type: authentication
      path: scripts
      language: JAVASCRIPT
