# -- stackhawk configuration for Azure Active Directory Resource Owner Password grant type --

app:
  applicationId: ${HAWK_APP_ID}
  env: Development
  host: http://localhost:3000
  openApiConf:
    filePath: openapi.yml
  autoPolicy: true
  autoInputVectors: true

  authentication:
    loggedInIndicator: ".*"   # This will always match, so we will never fall through to loggedOutIndicator
    loggedOutIndicator: "^$"  # This will never match, so we will never reauthenticate

    # AuthN Settings
    script:
      name: azure-ad-resource-owner-password.kts
      parameters:
        tenant: ${AAD_TENANT}       # The directory tenant that you want to log the user into. The tenant can be in GUID or friendly name format
        scope: ${AAD_SCOPE}         # OPTIONAL: A space-separated list of scopes, or permissions, that the app requires
      credentials:
        clientId: ${AAD_CLIENT_ID}  # The Application (client) ID that the Azure portal App registrations page assigned to your app
        username: ${AAD_USERNAME}   # Your AAD credentials username
        password: ${AAD_PASSWORD}   # Your AAD credentials password

    # AuthZ Settings
    tokenExtraction:
      type: TOKEN_PATH
      value: access_token
    tokenAuthorization:
      type: HEADER
      value: Authorization
      tokenType: Bearer
    testPath:
      path: /secured
      success: '.*200.*'

hawkAddOn:
  scripts:
    - name: azure-ad-resource-owner-password.kts
      path: hawkscripts
      type: authentication
      language: KOTLIN
