app:
  applicationId: ${YOUR_APP_ID}
  env: Keycloak
  host: http://localhost:8000
  openApiConf:
    path: "/openapi.json"
    #filePath: "openapi.json"
  authentication:
    loggedInIndicator: "HTTP/\d+\.\d+\s+(2[0-9][0-9]|3[0-9][0-9])"
    loggedOutIndicator: "HTTP/\d+\.\d+\s+(4[0-9][0-9])"
    # authn
    script:
      name: keycloak-client-credentials.kts
      parameters:
        issuer: http://${YOUR_DOMAIN}/auth/realms/${REALM_NAME}/protocol/openid-connect/token
        grantType: client_credentials
      credentials:
        clientId: ${YOUR_CLIENT_ID}
        clientSecret: ${YOUR_CLIENT_SECRET}
    # authz
    sessionScript:
      name: access-token-session.js
    testPath:
      path: /private
      success: '.*200.*'
hawkAddOn:
  scripts:
    - name: keycloak-client-credentials.js
      type: authentication
      path: scripts
      language: KOTLIN
    - name: access-token-session.js
      type: session
      path: scripts
      language: JAVASCRIPT
