app:
  applicationId: ${YOUR_APP_ID}
  env: Development 
  host: http://localhost:8000/
  autoPolicy: true
  autoInputVectors: true
  authentication:
    loggedInIndicator: "HTTP.*2[0-9][0-9]\\s*O[kK](\\s*)|HTTP.*3[0-9][0-9].*"
    loggedOutIndicator: "HTTP.*4[0-9][0-9](\\s*)Unauthorized.*" 
     # -- Customized Configuration for Authentication Scripting --
    # Specify the parameters required for POSTing to the token URL
    # parementers and credentials generally function the same, only credentials will be redacted throughout the StackHawk platform.
    script:
      name: auth.js
      parameters:
        issuer: https://${YOUR_AUTH0_DOMAIN}.us.auth0.com/oauth/token
        grant_type: password
        audience: ${YOUR_API_AUDIENCE}
      credentials:
        client_id: xxxXXXXxxxxXXXXxxxx ## \${CLIENT_ID}
        client_secret: xxxXXXXxxxxXXXXxxxx ## \${CLIENT_SECRET}
        username: test@email.com
        password: hawkScan1

    testPath:
      path: /api/external
      success: '.*200.*'
 
  # The location of the script directory should be relative to the stackhawk.yml file.
  hawkAddOn:
  scripts:
    - name: auth.js
      language: JAVASCRIPT
      type: authentication
      path: scripts
  