# -- stackhawk configuration for Keycloak Resource Owner Password grant type --
#
# This configuration file was tested against a Keycloak sample app found at:
#   https://github.com/keycloak/keycloak-quickstarts/tree/latest/nodejs/resource-server

app:
  applicationId: ${HAWK_APP_ID}
  env: Development
  host: http://localhost:3000
  openApiConf:
    filePath: openapi.yml
  autoPolicy: true
  autoInputVectors: true

  authentication:
    loggedInIndicator: ".*"   # This will always match, so we will never fall through to loggedOutIndicator
    loggedOutIndicator: "^$"  # This will never match, so we will never reauthenticate

    # AuthN Settings
    script:
      name: keycloak-resource-owner-password.kts
      parameters:
        baseUrl: ${KEYCLOAK_BASE_URL:http://127.0.0.1:8180}   # Your Keycloak base URL, e.g. http://127.0.0.1:8180
        realm: ${KEYCLOAK_REALM:quickstart}                   # Your Keycloak realm
      credentials:
        clientId: ${KEYCLOAK_CLIENT_ID:test-cli}  # Your Keycloak client ID
        username: ${KEYCLOAK_USERNAME:alice}      # Your Keycloak credentials username
        password: ${KEYCLOAK_PASSWORD:alice}      # Your Keycloak credentials password

    # AuthZ Settings
    tokenExtraction:
      type: TOKEN_PATH
      value: access_token
    tokenAuthorization:
      type: HEADER
      value: Authorization
      tokenType: Bearer
    testPath:
      path: /secured
      success: '.*200.*'

hawkAddOn:
  scripts:
    - name: keycloak-resource-owner-password.kts
      path: hawkscripts
      type: authentication
      language: KOTLIN

hawk:
  spider:
    base: false
