# stackhawk configuration for Azure Active Directory Client Credentials grant type with a shared secret
# https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret

app:
  applicationId: ${HAWK_APP_ID}
  env: Development
  host: http://localhost:3000
  openApiConf:
    filePath: openapi.yml
  autoPolicy: true
  autoInputVectors: true

  authentication:
    loggedInIndicator: ".*" # This will always match, so we will never fall through to loggedOutIndicator
    loggedOutIndicator: "^$" # This will never match, so we will never reauthenticate

    # AuthN Settings
    script:
      name: azure-ad-client-credentials.kts
      parameters:
        tenant: ${AAD_TENANT} # The directory tenant that you want to log the user into. The tenant can be in GUID or friendly name format
        scope: ${AAD_SCOPE} # The resource identifier (application ID URI) of the resource you want, affixed with the .default suffix, e.g. https://graph.microsoft.com/.default
      credentials:
        clientId: ${AAD_CLIENT_ID} # The Application (client) ID that the Azure portal App Registrations page assigned to your app
        clientSecret: ${AAD_CLIENT_SECRET} # The client secret that you generated for your app in the app registration portal

    # AuthZ Settings
    tokenExtraction:
      type: TOKEN_PATH
      value: access_token
    tokenAuthorization:
      type: HEADER
      value: Authorization
      tokenType: Bearer
    testPath:
      path: /secured
      success: '.*200.*'

hawkAddOn:
  scripts:
    - name: azure-ad-client-credentials.kts
      path: hawkscripts
      type: authentication
      language: KOTLIN
